config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  root "games#index"

  get "games", to:"games#auto_generation", as:"auto_generation"
  post "games", to:"games#manual_fill", as: "manual_fill"
  post "games/auto_fill", to:"games#auto_fill", as: "auto_fill"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/games_controller.rb
# frozen_string_literal: true

class GamesController < ApplicationController

  @@lock

  def index
    @deck = Game.initialize
    @lock = Game.initialize
    @@lock = @lock
  end


  def manual_fill
    @deck = parse_deck(params[:deck])
    if(@deck.nil?)
      flash.alert = "INCORRECT INPUT!!! NUMBERS ONLY (1-9)!!!"
      redirect_to root_path
      return
    end
    # Game.print_deck(@deck)

    message = Game.check_deck(@deck)
    flash.notice = message

    @lock = @@lock
    render "games/index"
  end

  def auto_fill
    @deck = parse_deck(params[:deck])
    if(@deck.nil?)
      flash.alert = "INCORRECT INPUT!!! NUMBERS ONLY (1-9)!!!"
      redirect_to root_path
      return
    end

    @lock = @@lock
    tmp = Game.auto_fill(@deck)

    if(tmp.nil?)
      flash.alert = "This deck cannot be solved!!!"
    else
      @deck = tmp
    end

    render "games/index"
  end

  def auto_generation
    @deck, @lock = Game.auto_generation
    @@lock = @lock
    render "games/index"
  end

  private

  def parse_deck(str)
    deck = Game.initialize
    rows = str.split('|')
    i = 0
    begin
      rows.each do |row|
        j = 0
        elements = row.split(',')
        elements.each do|elem|
          deck[i][j] = Integer(elem)
          if(deck[i][j] < 0 || deck[i][j] > 9)
            return nil
          end
          j += 1
        end
        i += 1
      end
    rescue ArgumentError
      return nil
    end
    return deck
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/games/index.html.erb
<head>
  <%= javascript_include_tag('render.js') %>
</head>

<div class="container">

  <div class="row">

    <div class="col-md-10">
      <% i = 0 %>
      <% @deck.each do|row|%>
        <div class="row">
          <% row.each do|elem|%>
            <% i += 1 %>
            <div class="col-md-1">

              <% if @lock[(i-1)/9][i-9*((i-1)/9)-1] == 1 && @deck[(i-1)/9][i-9*((i-1)/9)-1] != 0%>
                <input type="number" id="<%=i%>" value="<%= elem %>" min="1" max="9" readonly style="width: 50%; background: lightgray">
              <% else %>
                <input type="number" id="<%=i%>" value="<%= elem %>" min="1" max="9" style="width: 50%">
              <% end %>

              <% if(i%3==0) %>
                |
              <% end %>
            </div>
          <% end %>
        </div>
        <% if(i%27==0) %>
          <hr>
        <% else %>
          <br>
        <% end %>
        <br>
      <% end %>

    </div>

    <div class="col-md-2">
      <%=form_with(url: manual_fill_path) do |f|%>
        <%=f.hidden_field :deck, id:"deck" %>
        <%= f.submit value:"Check", :class => "btn btn-success btn-xs", :onclick=>"transform()" %>
      <%end %>
      <br>
      <%=form_with(url: auto_fill_path) do |f|%>
        <%=f.hidden_field :deck, id:"deck_auto" %>
        <%= f.submit value:"Auto-complete", :class => "btn btn-success btn-xs", :onclick=>"transform()"%>
      <%end %>
    </div>

  </div>

</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">

  <div class="collapse navbar-collapse">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <%= link_to "Start New",  root_path, :class => "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Auto Generation",  auto_generation_path, :class => "nav-link" %>
      </li>
    </ul>

  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Lab3</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag "application" %>

  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-aFq/bzH65dt+w6FI2ooMVUpc+21e0SRygnTpmBvdBgSdnuTN7QbdgL+OapgHtvPp" crossorigin="anonymous">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha2/dist/js/bootstrap.bundle.min.js" integrity="sha384-qKXV1j0HvMUeCBQ+QVp7JcfGl760yU08IQ+GpUo5hlbpg51QRiuqHAJz8+BrxE/N" crossorigin="anonymous"></script>
</head>

<body>
<%= render 'layouts/header' %>
<div class="container">
  <p class="notice text-primary"><%= notice %></p>
  <p class="alert text-danger"><%= alert %></p>
</div>
<%= yield %>
</body>
</html>